选课系统/course/urls.py
from django.contrib import admin
from django.urls import path, include
from course.views import *
from course.cbvs import ScheduleDeleteView, ScoreUpdateView, RateUpdateView, StudentCourseDetailView

import user
urlpatterns = [
    path('', to_home, name="course"),
    path('<slug:kind>/', home, name="course"),
    path('teacher/create_course', create_course, name="create_course"),
    path('teacher/view_detail/<int:course_id>', view_detail, name="view_detail"),
    path('teacher/create_schedule/<int:course_id>', create_schedule, name="create_schedule"),
    path('teacher/delete_schedule/<int:schedule_id>', delete_schedule, name="delete_schedule"),
    path('teacher/score/<int:pk>', ScoreUpdateView.as_view(), name="score"),
    path('teacher/handle_course/<int:course_id>/<int:handle_kind>', handle_course, name="handle_course"),

    path('student/view/<slug:view_kind>', view_course, name="view_course"),
    path('student/operate/<int:course_id>/<slug:operate_kind>', operate_course, name="operate_course"),

    path('student/evaluate/<int:pk>', RateUpdateView.as_view(), name="evaluate"),
    path('student/view_detail/<int:pk>', StudentCourseDetailView.as_view(), name="sview_detail"),
    path('admin/view/<slug:view_kind>', view_personnel, name="view_personnel"),
]

选课系统/scss/urls.py
# usr/bin/env python3
# -*- coding:utf-8- -*-
"""scss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from user.views import login, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('course/', include("course.urls")),

    path('', home),
]

选课系统/course/models.py
from django.db import models
import datetime
from user.models import Student, Teacher
from constants import COURSE_STATUS, COURSE_OPERATION


def current_year():
    # refer: https://stackoverflow.com/questions/49051017/year-field-in-django/49051348
    return datetime.date.today().year


class Course(models.Model):
    credits = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    semesters = [
        ("Autumn", "上"),
        ("Spring", "下")
    ]
    name = models.CharField(max_length=50, verbose_name="课程名")
    introduction = models.CharField(max_length=250, verbose_name="介绍")
    credit = models.IntegerField(verbose_name="学分")
    max_number = models.IntegerField(verbose_name="课程最大人数")

    year = models.IntegerField(verbose_name="年份", default=current_year)
    semester = models.CharField(max_length=20, verbose_name="学期", choices=semesters)

    # 未开始选课， 1
    # 开始选课，未结束选课 2
    # 结束选课， 3
    # 结课 4
    # 已打完分 5
    status = models.IntegerField(verbose_name="课程状态", default=1)

    teacher = models.ForeignKey(Teacher, verbose_name="课程教师", on_delete=models.CASCADE)

    def get_status_text(self):
        return COURSE_STATUS[self.status]

    def get_op_text(self):
        return COURSE_OPERATION[self.status]

    def get_current_count(self):
        courses = StudentCourse.objects.filter(course=self, with_draw=False)
        return len(courses)

    def get_schedules(self):
        schedules = Schedule.objects.filter(course=self)
        return schedules

    def __str__(self):
        return "%s (%s)" % (self.name, self.teacher.name)


def weekday_choices():
    weekday_str = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
    return [(i+1, weekday_str[i]) for i in range(7)]


class Schedule(models.Model):
    weekday = models.IntegerField(choices=weekday_choices(), verbose_name="日期")
    start_time = models.TimeField(verbose_name="上课时间")
    end_time = models.TimeField(verbose_name="下课时间")
    location = models.CharField(max_length=100, verbose_name="上课地点")
    remarks = models.CharField(max_length=100, verbose_name="备注", null=True, blank = True)

    start_week = models.IntegerField(verbose_name="第几周开始")
    end_week = models.IntegerField(verbose_name="第几周结束")

    intervals = [
        (1, "无间隔"),
        (2, "每隔一周上一次")
    ]
    week_interval = models.IntegerField(verbose_name="周间隔", choices=intervals, default=1)

    course = models.ForeignKey(Course, verbose_name="课程名", on_delete=models.CASCADE)

    def __str__(self):
        s = "第%s周-第%s周 " % (self.start_week, self.end_week)
        if self.week_interval == 2:
            s += "隔一周 "
        s += "%s %s-%s " % (self.get_weekday_display(), self.start_time.strftime("%H:%M"),
                            self.end_time.strftime("%H:%M"))
        s += "在%s" % self.location
        if self.remarks:
            s += " %s" % self.remarks
        return s



class StudentCourse(models.Model):
    create_time = models.DateTimeField(auto_now=True)
    with_draw = models.BooleanField(default=False)
    with_draw_time = models.DateTimeField(default=None, null=True)

    scores = models.IntegerField(verbose_name="成绩", null=True)
    comments = models.CharField(max_length=250, verbose_name="老师评价", null=True)

    rates = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    rating = models.IntegerField(verbose_name="学生评分", choices=rates, null=True, help_text="5分为最满意，最低分是1分")
    assessment = models.CharField(max_length=250, verbose_name="学生评价", null=True)

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

选课系统/course/forms.py
# usr/bin/env python
# -*- coding:utf-8- -*-
from django import forms
from .models import Course, Schedule, StudentCourse


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        exclude = ['status', 'teacher']


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        exclude = ["course"]


class ScoreForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ["student", "course", "scores", "comments"]

    student = forms.CharField(label="学生", disabled=True)
    # course = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    course = forms.CharField(label="课程", disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['student'] = self.instance.student
        self.initial['course'] = self.instance.course

    def clean_student(self):
        return self.initial['student']

    def clean_course(self):
        return self.initial['course']


class RateForm(forms.ModelForm):
    class Meta:
        model = StudentCourse
        fields = ["course", "scores", "comments", "rating", "assessment"]

    course = forms.CharField(label="课程", disabled=True)
    scores = forms.IntegerField(label="成绩", disabled=True)
    comments = forms.CharField(label="老师评价", disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['course'] = self.instance.course
        self.initial['scores'] = self.instance.scores
        self.initial['comments'] = self.instance.comments

    def clean_course(self):
        return self.initial['course']

    def clean_scores(self):
        return self.initial['scores']

    def clean_comments(self):
        return self.initial['comments']

选课系统/course/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, reverse, redirect
from django.db.models import Q

from constants import INVALID_KIND, INVALID_REQUEST_METHOD, ILLEGAL_KIND
from course.forms import CourseForm, ScheduleForm
from course.models import Course, StudentCourse, Schedule
from user.util import get_user

from django.utils import timezone
from user.models import Student, Teacher


def to_home(request):
    kind = request.session.get('kind', '')
    return redirect(reverse("course", kwargs={"kind": kind}))


# 跳转函数
def home(request, kind):
    if kind == "teacher":
        return teacher_home(request)
    elif kind == "student":
        return student_home(request)
    elif kind == "admin":
        return admin_home(request)
    return HttpResponse(INVALID_KIND)


# 教师主页
def teacher_home(request):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    context = {"info": info}
    q = Q(teacher=user)
    if is_search:
        q = q & Q(name__icontains=search_key)
        context["search_key"] = search_key

    context["course_list"] = Course.objects.filter(q).order_by('status')

    return render(request, 'course/teacher/home.html', context)


# 学生主页
def student_home(request):
    return redirect(reverse("view_course", kwargs={"view_kind": "current"}))


# 管理员主页
def admin_home(request):
    kind = "admin"
    user = get_user(request, kind)

    if not user:
        return redirect('login', kind=kind)

    info = {
        "admin_pr": user.admin_pr,
        "kind": kind
    }

    context = {
        "info": info,
    }

    return render(request, 'course/admin/home.html', context)


# 显示管理员操作的对象：学生或教师
def view_personnel(request, view_kind):
    """
     :param request:
     :param view_kind:
             1: "学生",
             2: "老师",
     :return:
     """
    kind = "admin"
    user = get_user(request, kind)

    # 非法请求对象则返回登录页面
    if not user:
        return redirect('login', kind=kind)

    info = {
        "admin_pr": user.admin_pr,
        "kind": kind
    }

    context = {
            "info": info,
            "view_kind":view_kind
        }

    # 判断是否需要搜索
    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    if view_kind in ["student", "teacher"]:
        # 是否查询
        if is_search:
            context["search_key"] = search_key
            if view_kind == "student":
                # 是否精确搜索
                if len(search_key) == 10:
                    q1 = search_key[:4]
                    q2 = search_key[4:]
                    q = Q(name__icontains=search_key) | Q(number__icontains=search_key) | (
                                Q(grade=q1) & Q(number=q2))
                else:
                    q = Q(name__icontains=search_key) | Q(number__icontains=search_key)

                context["stu_list"] = Student.objects.filter(q).order_by('grade', 'number')
            elif view_kind == "teacher":
                # 是否精确搜索
                if len(search_key) == 10:
                    q1 = search_key[:3]
                    q2 = search_key[3:]
                    q = Q(name__icontains=search_key) | Q(number__icontains=search_key) | (Q(department_no=q1) & Q(number=q2))
                else:
                    q = Q(name__icontains=search_key) | Q(number__icontains=search_key)

                context["tea_list"] = Teacher.objects.filter(q).order_by('department_no', 'number')
        else:   # 否则显示全部人员
            if view_kind == "student":
                context["stu_list"] = Student.objects.all().order_by('grade', 'number')
            elif view_kind == "teacher":
                context["tea_list"] = Teacher.objects.all().order_by('department_no', 'number')
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/admin/home.html', context)


# 创建课程
def create_course(request):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.status = 1
            obj.teacher = user

            obj.save()
            return redirect(reverse("course", kwargs={"kind": "teacher"}))
    elif request.method == 'GET':
        form = CourseForm()
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/teacher/create_course.html', {'info': info, 'form': form})


# 创建课程时刻表
def create_schedule(request, course_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)

    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.course = course
            obj.save()

            return redirect(reverse("view_detail", kwargs={"course_id": course_id}))
    elif request.method == 'GET':
        form = ScheduleForm()
    else:
        return HttpResponse(INVALID_REQUEST_METHOD)

    return render(request, 'course/teacher/create_schedule.html', {'info': info, 'form': form, "course": course})


def delete_schedule(request, schedule_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    schedule = Schedule.objects.get(pk=schedule_id)

    course_id = request.GET.get("course_id") or schedule.course.id

    schedule.delete()

    return redirect(reverse("view_detail", kwargs={"course_id": course_id}))


# 课程操作函数
def handle_course(request, course_id, handle_kind):
    """
    :param request:
    :param course_id:
    :param handle_kind:
            1: "开始选课",
            2: "结束选课",
            3: "结课",
            4: "给分完成"
    :return:
    """
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)
    if course.status == handle_kind and course.status < 5:
        if course.status == 4:
            scs = StudentCourse.objects.filter(course=course)
            all_given = True
            res = ""
            for sc in scs:
                if sc.scores is None:
                    all_given = False
                    res += "<div>%s 未打分</div>" % sc.student

            if all_given:
                course.status += 1
                course.save()
                return redirect(reverse("view_detail", kwargs={"course_id": course.id}))
            else:
                return HttpResponse(res)
        else:
            course.status += 1
            course.save()

    course_list = Course.objects.filter(teacher=user)
    return render(request, 'course/teacher/home.html', {'info': info, 'course_list': course_list})


def view_detail(request, course_id):
    user = get_user(request, "teacher")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "teacher"}))

    info = {
        "name": user.name,
        "kind": "teacher",
    }

    course = Course.objects.get(pk=course_id)
    c_stu_list = StudentCourse.objects.filter(course=course)
    sche_list = Schedule.objects.filter(course=course)

    context = {
        "info": info,
        "course": course,
        "course_students": c_stu_list,
        "schedules": sche_list
    }

    if course.status == 5:
        sorted_cs_list = sorted(c_stu_list, key=lambda cs: cs.scores)
        context["sorted_course_students"] = sorted_cs_list

    return render(request, "course/teacher/course.html", context)


def view_course(request, view_kind):
    """
    :param view_kind:
        current: 查看当前课程
        is_end: 查看结课课程
        select: 选课
        withdraw: 撤课
    """
    user = get_user(request, "student")
    if not user:
        return redirect(reverse("login", kwargs={"kind": "student"}))

    is_search = False
    search_key = ""
    if request.method == "POST":
        search_key = request.POST.get("search")
        if search_key:
            is_search = True

    info = {
        "name": user.name,
        "kind": "student",
    }

    course_list = []

    if view_kind in ["select", "current", "withdraw", "is_end"]:
        if view_kind == "select":
            q = Q(status=2)
            if is_search:
                q = q & (Q(name__icontains=search_key) | Q(teacher__name__icontains=search_key))

            course_list = Course.objects.filter(q)

            my_course = StudentCourse.objects.filter(Q(student=user) & Q(with_draw=False))
            my_cids = [c.course.id for c in my_course]
            course_list = [c for c in course_list if c.id not in my_cids]
        else:
            q = Q(student=user) & Q(with_draw=False)
            if is_search:
                q = q & (Q(course__name__icontains=search_key) | Q(course__teacher__name__icontains=search_key))
            my_course = StudentCourse.objects.filter(q)
            if view_kind == "current":
                course_list = [c.course for c in my_course if c.course.status < 4]
            elif view_kind == "withdraw":
                course_list = [c.course for c in my_course if c.course.status == 2]
            elif view_kind == "is_end":

选课系统/templates/course/teacher/course.html
{% extends "course/nav.html" %}
{% block title %}课程详情{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
    <h3>课程详情<input class="button right-button" type="button" value="返回主页"
                   onclick='window.open("{% url 'course' 'teacher'%}")'/></h3>
    <table class="item-list detail-list">
        <thead>
            <tr>
                <th>课程编号</th>
                <th>名称</th>
                <th>学分</th>
                <th>当前人数/总人数</th>
                <th>年份</th>
                <th>学期</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ course.id }}</td>
                <td>{{ course.name }}</td>
                <td>{{ course.credit }}</td>
                <td>{{ course.get_current_count }}/{{ course.max_number }}</td>
                <td>{{ course.year }}</td>
                <td>{{ course.get_semester_display }}</td>
            </tr>
        </tbody>
    </table>

    <h3>上课时间<input class="button right-button" type="button" value="添加时间表" onclick='window.open("{% url 'create_schedule' course.id%}")'/></h3>
    <table class="item-list schedule-list">
        <thead>
            <tr>
                <th class="schedule-no">编号</th>
                <th class="schedule-no">详情</th>
                <th class="schedule-no">操作</th>
            </tr>
        </thead>
        <tbody>
            {% for schedule in schedules %}
            <tr>
                <td>{{ schedule.id }}</td>
                <td>{{ schedule }}</td>
                <td>
                    <input class="button" type="button" value="删除"
                           onclick='window.open("{% url 'delete_schedule' schedule.id%}?course_id={{ course.id }}")'/>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>学生列表
        {% if course.status == 4 %}
            <input class="button right-button" type="button" value="给分完成" onclick='location.href="{% url 'handle_course' course.id 4%}"' />
        {% endif %}
    </h3>
    <table class="item-list student-list">
        <thead>
            <tr>
                <th class="student-no">学生学号</th>
                <th class="student-name">学生姓名</th>
                <th class="student-email">学生邮箱</th>
                <th class="student-score">得分</th>
                <th class="student-comments">评价</th>
                <th class="operation">操作</th>
            </tr>
        </thead>
        <tbody>
            {% for cs in course_students %}
            <tr>
                <td>{{ cs.student.get_id}}</td>
                <td>{{ cs.student.name }}</td>
                <td>{{ cs.student.email }}</td>
                <td>
                    {% if cs.scores == None %}-{% endif %}
                    {% if cs.scores != None %}{{ cs.scores }}{% endif %}
                </td>
                <td>
                    {% if cs.scores == None %}-{% endif %}
                    {% if cs.scores != None %}{{ cs.comments }}{% endif %}
                </td>
                <td class="operation">
                    {% if course.status == 4 %}
                        {% if cs.scores == None %}
                            <input class="button right-button" type="button" value="给分"
                               onclick='location.href="{% url 'score' cs.id%}"' />
                        {% else %}
                            <input class="button right-button" type="button" value="修改成绩"
                               onclick='location.href="{% url 'score' cs.id%}?update=1"' />
                        {% endif %}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if course.status == 5 %}
    <h3>学生评价</h3>
    <table class="item-list student-list">
        <thead>
            <tr>
                <th class="student-score">学生评分</th>
                <th class="student-comments">学生评价</th>
            </tr>
        </thead>
        <tbody>
            {% for cs in sorted_course_students %}
            {% if cs.rating != None %}
            <tr>
                <td>{{ cs.rating }}</td>
                <td>{{ cs.assessment }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

选课系统/templates/course/teacher/create_course.html
{% extends "course/nav.html" %}
{% block title %}创建课程{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>创建课程</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="创建"/>
                <input type="button" value="返回"  onclick='window.open("{% url 'course' "teacher"%}")' />
            </div>
        </form>
    </div>
{% endblock %}

选课系统/templates/course/teacher/create_schedule.html
{% extends "course/nav.html" %}
{% block title %}创建时刻表{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>创建时刻表:&nbsp;&nbsp;&nbsp;&nbsp;[{{ course.id }}] {{ course.name }}</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="创建"/>
                <input type="button" value="返回"  onclick='window.open("{% url 'view_detail' course.id%}")' />
            </div>
        </form>
    </div>
{% endblock %}

选课系统/templates/course/teacher/home.html
{% extends "course/nav.html" %}
{% block title %}HomePage{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
    <div class="main-container">
        <div class="main-bar">
            <form class="search-form" method="post">
                {% csrf_token %}
                <input class="input" id="search-key" type="text" name="search" {% if search_key != None %}value="{{ search_key }}" {% endif %}/>
                <input class="button" type="submit" value="搜索课程" />
            </form>

            <input class="button right-button" type="button" value="创建课程"  onclick='window.open("{% url 'create_course' %}")' />
        </div>
        <table class="item-list course-list">
            <thead>
                <tr>
                    <th class="course-no">课程编号</th>
                    <th class="course-name">名称</th>
                    <th class="course-credit">学分</th>
                    <th class="course-number">当前人数<br>/总人数</th>
                    <th class="course-year">年份</th>
                    <th class="course-semester">学期</th>
                    <th class="course-status">状态</th>
                    <th class="course-operation">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for course in course_list %}
                    <tr id="course-id-{{ course.id }}">
                    <td class="course-no">{{ course.id }}</td>
                    <td class="course-name">{{ course.name }}</td>
                    <td class="course-credit">{{ course.credit }}</td>
                    <td class="course-number">{{ course.get_current_count }}/{{ course.max_number }}</td>
                    <td class="course-year">{{ course.year }}</td>
                    <td class="course-semester">{{ course.get_semester_display }}</td>
                    <td class="course-status">{{ course.get_status_text }}</td>
                    <td class="course-operation">
                        {% if course.status < 4 %}
                            <input class="button right-button" type="button" value="{{ course.get_op_text }}"
                              onclick='location.href="{% url 'handle_course' course.id course.status %}"' />
                        {% endif %}
                        {% if course.status == 4 %}
                        {# 结课后给分 #}
                            <input class="button right-button" type="button" value="{{ course.get_op_text }}"
                                   onclick='location.href="{% url 'view_detail' course.id %}"' />
                        {% else %}
                            <input class="button right-button" type="button" value="查看详情"
                                   onclick='location.href="{% url 'view_detail' course.id %}"' />
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

选课系统/templates/course/teacher/score.html
{% extends "course/nav.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% load static %}
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <h3>{{ title }}</h3>
    <div class="form create-update-from">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div class="submit-button">
                <input type="submit" value="确定"/>
                <input type="button" value="返回"  onclick='location.href="{{ return_url }}"' />
            </div>
        </form>
    </div>
{% endblock %}